### ISSUE TITLE
issue for build windows

### ISSUE THREAD

**Issue by yb156784961** [Teach2Breach/Tempest#9] opened 2024-09-27 15:35 UTC
When I run the command `build windows exe *.*.*.* 443 2 50` in conduit.exe

error[E0433]: failed to resolve: use of undeclared crate or module `alloc`
  --> /root/Tempest/modules_wip/whoami/src/lib.rs:30:1
   |
30 | use_litcrypt!("ageofmachine");
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `alloc`
   |
   = help: add `extern crate alloc` to use the `alloc` crate
   = help: consider importing this module:
           std::vec
   = note: this error originates in the macro `use_litcrypt` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: use of undeclared crate or module `alloc`
  --> /root/Tempest/modules_wip/whoami/src/lib.rs:30:1
   |
30 | use_litcrypt!("ageofmachine");
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `alloc`
   |
   = help: add `extern crate alloc` to use the `alloc` crate
   = help: consider importing this module:
           std::string
   = note: this error originates in the macro `use_litcrypt` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: use of undeclared crate or module `alloc`
  --> /root/Tempest/modules_wip/whoami/src/lib.rs:30:1
   |
30 | use_litcrypt!("ageofmachine");
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `alloc`
   |
   = help: add `extern crate alloc` to use the `alloc` crate
   = help: consider importing this struct:
           std::string::String
   = note: this error originates in the macro `use_litcrypt` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0433`.
error: could not compile `whoami` (lib) due to 3 previous errors

**Comment by Teach2Breach** [comment] 2024-09-27 15:52
looks like an issue with the whoami module. interesting because no updates have been made to that module for a month. maybe something changed with a dependency. I'll take a look today. Thanks for reporting.

**Comment by Teach2Breach** [comment] 2024-09-27 20:47
this is a weird one... issue seems to be with litcrypt2, though I am having a hard time understanding how the macro isn't working correctly when it did previously with that version. best guess is that litcrypt2 needs an update because of some updates to rust or cargo. I did some testing falling back to the original litcrypt crate (not litcrypt2) and it works fine, so until I figure out whats wrong with litcrypt2 macro, I'll just push updates here to switch back to original litcrypt.

Given that litcrypt2 is used throughout the 2 currently available windows implants (not just in the whoami module), I'll need to apply updates in several places. Shouldn't take long. I'd guess I'll have this all sorted within 24 hours.

Once I test and push those updates and verify implants are building cleanly again, I'll post another comment here to close. Again, thanks for the heads up.

**Comment by Teach2Breach** [comment] 2024-09-27 20:48
on another note, this may be a good reason to create an implant build that uses API hashing instead of relying on litcrypt as a dependency, since I don't have a ton of faith in the support of litcrypt repos. I'll put that down as a todo on the devlog as well

**Comment by Teach2Breach** [comment] 2024-09-27 21:57
should be all fixed now. I changed every use of litcrypt2 to use the original litcrypt crate. please let me know if you have any additional issues. Closing this issue as I have confirmed the fix with testing. Please open a new issue if you run into any additional problems.

I also made some notes to reduce future dependency on litcrypt and improve API name obfuscation, as well as more robust general string encryption throughout. That progress will be tracked in the devlog.

**Closed as completed by Teach2Breach** 2024-09-27 21:57 UTC

**Comment by Teach2Breach** [comment] 2024-09-27 22:07
Note that I am also still going to investigate the issues with litcrypt2 further. Will report any discovered issues to the appropriate dependency owner.
